---
title: Quiz time!
hero_image: images/banner.png
description: Create an interactive quiz app!
version: 4
listed: false
copyedit: false
last_tested: '2021-03-26'
steps:
  - title: You will make
  - title: Create your first question
  - title: Check the answer
  - title: Add more questions
    completion:
      - engaged
  - title: Add a score
  - title: Keep score
  - title: Show one question at a time
  - title: Show the next question
    completion:
      - internal
  - title: Finish the quiz
    completion:
      - external
  - title: Challenge
    challenge: true
